name: Semantic Versioning and Tagging

on:
  push:
    branches:
      - master  # Trigger when pushing to master

permissions:
  contents: write  # Allow GitHub Actions to push content to the repo
  actions: write   # Allow GitHub Actions to create a tag and trigger actions

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Run Semantic Release (version increment and tag creation)
      - name: Run Semantic Release (version increment and tag creation)
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.SEMVER }}
