name: Semantic Versioning and Tagging

on:
  push:
    branches:
      - master  # target brnach to "listen" for PR merges

permissions: # to allow the auto created gitactions tocken to push changes to the repo
  contents: write

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semantic Release (version increment and tag creation)
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
