name: Upload Binaries on Tag Push

on:
  push:
    tags:
      - "*"  # Matches tags like v1.0.0, v2.1.3, etc.

jobs:
  upload-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment and build the binaries
      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Build Go executable for Linux, Mac, and Windows
        run: |
          GOOS=linux GOARCH=amd64 go build -o nnDiscordBot-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o nnDiscordBot-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -o nnDiscordBot-windows-amd64.exe

      # Upload Go executables to GitHub Releases
      - name: Upload Go executables to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nnDiscordBot-linux-amd64
            nnDiscordBot-darwin-amd64
            nnDiscordBot-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.SEMVER }}
